import { TokenTableColumn } from '../scheme/type';

export const COLUMNS: TokenTableColumn[] = [
  { key: 'rank', label: '#', sortable: false, width: '40px', align: 'left' },
  { key: 'token', label: 'Token', sortable: true, width: '150px' },
  { key: 'exchange', label: 'Exchange', sortable: true, width: '320px' },
  {
    key: 'priceUsd',
    label: 'Price',
    sortable: false, // TODO: no param in the API for the price column
    width: '300px',
    align: 'right',
  },
  {
    key: 'mcap',
    label: 'Market Cap',
    sortable: true,
    width: '120px',
    align: 'right',
  },
  {
    key: 'volumeUsd',
    label: 'Volume 24h',
    sortable: true,
    width: '120px',
    align: 'right',
  },
  {
    key: 'tokenCreatedTimestamp',
    label: 'Time',
    sortable: true,
    width: '80px',
    align: 'center',
  },
  {
    key: 'priceChange5m',
    label: '5m',
    sortable: true,
    width: '100px',
    align: 'center',
  },
  {
    key: 'priceChange1h',
    label: '1h',
    sortable: true,
    width: '100px',
    align: 'center',
  },
  {
    key: 'priceChange6h',
    label: '6h',
    sortable: true,
    width: '100px',
    align: 'center',
  },
  {
    key: 'priceChange24h',
    label: '24h',
    sortable: true,
    width: '100px',
    align: 'center',
  },
  {
    key: 'buys',
    label: 'Buys',
    sortable: true,
    width: '80px',
    align: 'center',
  },
  {
    key: 'sells',
    label: 'Sells',
    sortable: true,
    width: '80px',
    align: 'center',
  },
  {
    key: 'liquidity',
    label: 'Liquidity',
    sortable: true,
    width: '120px',
    align: 'right',
  },
  {
    key: 'audit',
    label: 'Audit',
    sortable: false,
    width: '250px',
    align: 'center',
  },
];
